### PR TITLE
common.notification: Only show notifications when available

### PR DESCRIPTION
**Pull request by bubuntux**
This it's a new option in the preferences windows, you can choose if only want receive notification when available, this is a very common option in other IMs.

btw have fun :P

### CODE REVIEW

**Comment by c10ud** [comment]
@bubuntux also please get back on track because your git repo is diverging a bit from emesene/emesene

**Comment by bubuntux** [comment]
Done, actually i keep the track, i send the pull request before a lot of commits, anyway it's clean now :)

**Comment by bubuntux** [comment]
Are you going to accept my pull request??

**Comment by c10ud** [comment]
indeed i am, i got busy with other stuff and completely forgot about it, sorry

**Pull request merged**
