### PR TITLE
Add OS X system pictures to Avatar Manger

### PR DESCRIPTION
**Pull request by ghost**
OS X users can see the installed system pictures under system pictures in the avatar chooser

### CODE REVIEW

**Comment by Sbte** [comment]
4, just like in the rest of the files.

**Comment by ghost** [comment]
Is this right then? http://pastebin.com/JPvMaAju

**Comment by Sbte** [comment]
Yes, looks like it

**Comment by ghost** [comment]
Done

**Comment by c10ud** [comment]
pulled thanks

**Pull request closed without merging**
