### PR TITLE
Preferences on windows won't open if there's no win32com module

### PR DESCRIPTION
**Pull request by arielj**
This commit uses only python modules to do the same, removing win32api dependency

I don't push my own commit to the emesene github because i'm not really sure how to do it :P

It's just the latest commit, I don't know how to revert the other changes that were never merged on the main emesene branch, should I re-fork the emesene git? some help will be appreciated :P

### CODE REVIEW

**Comment by c10ud** [comment]
you're currently in conflict with emesene/master - first try:
git pull emesene master
git push origin master

**Comment by c10ud** [comment]
about reverting other changes.. you could just delete your master and create a new one from emesene/master, but try fixing it first :D

**Comment by arielj** [comment]
I made those two command fixing the merge conflicts, I think I already reverted my other changes on the merges in between to resolve conlicts too :P

can you pull this now?

**Comment by c10ud** [comment]
trying :D

**Comment by c10ud** [comment]
pulled, yay

**Pull request closed without merging**
