### PR TITLE
Declare is_reconnecting in Login

### PR DESCRIPTION
**Pull request by Stiveknx**
(so it won't throw an error)

Traceback (most recent call last):
  File "/home/stive/emesene-fork/emesene/emesene/gui/gtkui/Login.py",
line 402, in _on_account_key_release
    if event.keyval == gtk.keysyms.Tab and not self.is_reconnecting:
AttributeError: 'Login' object has no attribute 'is_reconnecting'

### CODE REVIEW

**Comment by lfottaviano** [comment]
I haven't seen that you were calling `is_reconnecting` in the base class also, thats why the value wasn't being changed.

**Comment by lfottaviano** [comment]
Did you test it? Is it working?

**Comment by lfottaviano** [comment]
Also, Isn't better to override `_on_account_key_release` on `ConnectingWindow` ? And removing `is_reconnecting` and unneeded things

**Comment by Sbte** [comment]
I just reverted the change. If you come up with something working, then please feel free to open a new pull request.

**Pull request closed without merging**
