### PR TITLE
Solution for #1236

### PR DESCRIPTION
**Pull request by moneycat**
Add im_context_filter_keypress for input method checking.

### CODE REVIEW

**Comment by Sbte** [comment]
Well, rather than fixing this just for gtk2, you might as well try to fix this for both gtk2 and gtk3. How about

`if event.keyval in (gtk.keysyms.Return, gtk.keysyms.KP_Enter) and not event.state:`

**Comment by moneycat** [comment]
@Sbte I do not change the part of gtk3 code of the on_key_press_event function. There still exists the check you provided in line 201. Thanks.

**Comment by moneycat** [comment]
The developer of gcin suggest that maybe we can check via gtk-im-context-filter-keypress. I'll do some test and rewrite code generally.

**Comment by moneycat** [comment]
I add the im_context_filter_keypress function to check if there exists input method for the event. It works fine for my gtk-based IM but I have no other environments for testing.

I don't know how to let  the pull just one commit. Should I remove the repository, re-fork, and do things again?

**Pull request merged**
