### PR TITLE
Added plugin description column in the plugin list

### PR DESCRIPTION
**Pull request by manuargue**
The plugin description is obtained from the attribute _description of the Plugin class. So this must be modified in that class and not in another one; otherwise 'No description' will be displayed.

It's my first commit, correct me if I'm wrong :)

### CODE REVIEW

**Comment by Sbte** [comment]
I like the idea, but maybe it's better to add the description below the name? Mainly for long names and long descriptions. And maybe make the name bold then to make it easier to distinguish the name and the description.

**Comment by manuargue** [comment]
ok! I will work on it..
thanks

**Comment by Sbte** [comment]
Pulled. Thanks!

Maybe one small hint for next time:

git fetch upstream
git rebase upstream/master

will avoid the merge commit.

**Comment by manuargue** [comment]
thanks Sbte!
and thanks for the hint.. I'm new with git, my mistake

**Comment by Sbte** [comment]
No problem at all. It's easy for us to fix, but it's probably nice for you to know how to do it ;)

**Comment by Fabioamd87** [comment]
why descriptions are displayed only on installed plugins?

**Comment by Sbte** [comment]
Because they weren't downloaded from the repository before. They are now, so it should be very easy to add.

**Pull request closed without merging**
