### PR TITLE
Temporary solution for #1236

### PR DESCRIPTION
**Pull request by moneycat**
I add a gtk3 check for key-press-event

### CODE REVIEW

**Comment by c10ud** [comment]
@pepeleproso said the method isn't present in gtk3 so the workaround is good but you have to fix this pull request (only one commit please) and indentation (4 spaces)

**Comment by Sbte** [comment]
I don't get it. You change something for gtk2 only where you said gtk3 was broken.

**Comment by pepeleproso** [comment]
could you try something. In "on_key_press_event" function replace the return True by return False that should tell gtk to execute other signals handlers

**Comment by moneycat** [comment]
My system environment is Ubuntu 12.04 LTS x86_64 with gnome-shell (but remove unity).

@pepeleproso I roll-back to the original version and change the "return True" as "return False" in "on_key_press_event". Now the ENTER made a new-line in TextBox. There's also messages in console: [10:19:29 WARNING papyon.p2p] Trying to publish an empty MSNObject.

@c10ud I'll try. Thanks.

**Pull request closed without merging**
