### PR TITLE
Try to fix Asian words in MSN protocol.

### PR DESCRIPTION
**Pull request by chy168**
We should use Unicode hex as message body.
Just tested Chinese by "Hello 台灣! (F)"

### CODE REVIEW

**Comment by c10ud** [comment]
i'll wait your response on the commit and pull if ok :)

**Comment by chy168** [comment]
OK, I confirm this problem happened in e3.msn, and papyon is work without this patch.
I think we should apply this commit in e3.msn library.

**Comment by c10ud** [comment]
ok pulled

**Comment by c10ud** [comment]
closing the issue

**Pull request closed without merging**
