### PR TITLE
Repull, fixes to Dialog.py

### PR DESCRIPTION
**Pull request by Mystro256**
See my last pull request for more info :)

Edit: I recommited it again

### CODE REVIEW

**Comment by c10ud** [comment]
you didn't fix my complaints

**Comment by Sbte** [comment]
Also, I think this doesn't belong here. I guess you can derive a dialog from the dialog class and use that in the plug-in.

**Comment by Mystro256** [comment]
@c10ud
I reset my repo and recommited it

@Stbe
Haha well this just seemed easier, feel free to do it yourself though ;), just seemed like a lot of work for no reason

**Comment by Sbte** [comment]
The capital madness of last time is still there.

**Comment by Mystro256** [comment]
Well what would you suggest? 

It's a window title, and the other hints have all capitals. Unless you would prefer "Format Help N/A"? What would be prefered?

**Comment by Sbte** [comment]
Actually, what you do there doesn't do what you want. There are no [$b], etc... tags for anything but groups and nicks, but the window says so. So I guess you have to make a new window anyway.

**Comment by Mystro256** [comment]
Ah, true say, I'll leave that to someone else, I'm no good with GTK. I may learn it later if I have time.

**Comment by Sbte** [comment]
You don't have to know gtk. You just have to know how our dialog class works ;)

Anyway, since this has to be changed anyway, better just commit it to the plugins repo.

**Pull request closed without merging**
