### PR TITLE
Qt4

### PR DESCRIPTION
**Pull request by GVisconti84**
Don't know exactly why it says 15 commits :/ Did I mess up something? However the changed files are correct :P

### CODE REVIEW

**Comment by c10ud** [comment]
because i rebased everything and github is crazy, in fact, i just pull, rebase and push and they will be 2 or three... however i  can give you push access if you want, so you can operate on emesene/master directly

**Comment by Sbte** [comment]
The thing is that you have merge commits in your branch. To get rid of them, you have to git reset your branch. 

https://github.com/emesene/emesene/wiki/GitHowTo

Generally, don't pull after you committed something unless you rebase properly ;)

**Comment by c10ud** [comment]
pulled

**Comment by GVisconti84** [comment]
Oh, Ok, I've read the link, there's always something new to learn eheheh (I'm not a Git guru :P)
For me it is ok to have push access, as long as everybody agrees. But I'd need proper instructions on how to do it without messing around :P

**Pull request closed without merging**
