### PR TITLE
Close emesene with keyboard on OS X

### PR DESCRIPTION
**Pull request by joshf**
Close emesene with command Q

### CODE REVIEW

**Comment by joshf** [comment]
My python doesnt go that far....

**Comment by Sbte** [comment]
`gtk.gdk.META_MASK or gtk.gdk.CONTROL_MASK`

**Comment by joshf** [comment]
If someone wants to implement this for me, your welcome to it. I'm
away till the end of June so dont have access to my mac.

On 2 May 2012 04:49, Sven
reply@reply.github.com
wrote:

**Comment by c10ud** [comment]
i think this is ok as it is because if you | them (bitwise or) you'll have to press ctrl+meta while if you or them (pythonic or) it will always choose the first

if i'm wrong, just prove it

**Comment by joshf** [comment]
Your right, but command C (copy) and command V (paste) work, so it
would be logical for command Q to work

On 4 May 2012 00:33, Riccardo
reply@reply.github.com
wrote:

**Pull request merged**
