### PR TITLE
Don't focus the window if you got disconnect

### PR DESCRIPTION
**Pull request by Stiveknx**
If you switch window than, got disconnect, emesene "focus" his window...
This is bad, especially if I'm in chrome for example typing something and ~le wild window appears, so...

### CODE REVIEW

**Comment by Stiveknx** [comment]
I added an option to ask if the user really wants  to quit or just send to tray...

**Comment by lfottaviano** [comment]
Suggestion:

1) Only a question, Is `is_reconnecting` necessary?.  Also `is_reconnecting = true` true is not defined, I think you mean True. :)  

3) I don't agree with the "ask" thing, unless you have a "Don't ask again" option.

**Comment by Stiveknx** [comment]
1)
Yeah, typo, (but here in my code is True, I think I edited after commit (It works with true also, so I didn't notice before))
If I don't use is_reconnecting, how I'll know  that if the user is reconnecting or not?
I tought about the reconnect_timer_id, but when the function is called it's remove, so It will always be None  in _on_account_key_release ...
2)
Sure, I forgot about that. I also agree with, but in this case only with an option in configuration ... Unless, thre's a way to ask that marking with a option to do not ask again (like firefox does when you're closing multi-tabs). I only found the yes_no in emesene DOC, would need implementation ...

**Comment by Sbte** [comment]
Could you try to merge all those commits into one? For example using interactive rebase.

**Pull request merged**
