### PR TITLE
Bugs

### PR DESCRIPTION
**Pull request by astagi**
Some bugs solved, emesene ready for synch and papyon patch (  see https://bugs.freedesktop.org/show_bug.cgi?id=33332 )

### CODE REVIEW

**Comment by c10ud** [comment]
the diff is quite huge, and i don't like the gtk stuff being in protocol.... can you check it applies cleanly to emesene/master? also, the biggest issue is with gtk being in e3

**Comment by astagi** [comment]
Hi...I know that importing gtk in e3 doesn't like to you, but it's the only way to make a thumb to send as preview...I could move it in another place, but it would be the same thing...For the other issue, I didn't understand what is the problem with "diff"... Isn't it right?? You can't apply this only for the big dimension???

**Comment by c10ud** [comment]
last time i pulled from mariano i got horrible conflicts..i see your branch is ~ to his.. anyway i'll try later..but first i'd like to get this preview thing solved -- e3/\* is definitely not the folder for gtk

**Comment by astagi** [comment]
Solved in my last commit :) Found another way using Image lib... With repo I don't know what's happened, I fetch from emesene/emesene every time and I pull requests into Mariano repo ( and emesene/emesene as I did in this case )..

**Comment by Sbte** [comment]
Try to pull and reset your tree before you make your own commits. Don't merge or rebase. That's what I learned the hard way :P

This is what I usually do:

If my tree is clean:

git pull upstream master

if it isn't:

git reset --hard origin
git pull upstream master
git reset --hard upstream/master

Then you can just cherry pick the commits from the branch where you have your commits into the main tree. And then push with push -f to resolve the conflict with your own github tree that you just created. 

Your tree is probably messed up because you merged upstream changes into your tree after you made changes to it. If you  see commits like "Merge branch xxx" in your commit log, you're most likely in a bad situation. You have 4 of those.

**Pull request merged**
