### PR TITLE
improve some suff

### PR DESCRIPTION
**Pull request by jamesaxl**
i hope that you will like it ;)

### CODE REVIEW

**Comment by Sbte** [comment]
See my comments on

2f7765530f9a64b83cde2c73ff0e22d543f51c42
d269ae49bd98a67b28aeb8ba96c1c480ee50b135

**Comment by Sbte** [comment]
General idea of my comments:

I don't think any of those changes make emesene more usable (more likely less usable).

**Comment by jamesaxl** [comment]
no problem , think i''m going to care about papyon now :)

**Comment by c10ud** [comment]
Is there some rationale behind this loads of changes? Can you elaborate a bit? Or shall I close/discard this pull request because you changed your mind?

**Comment by jamesaxl** [comment]
you can close it no problem as sbte said , emesene didn't need to this patch :)

**Pull request closed without merging**
