### PR TITLE
My first Fixed

### PR DESCRIPTION
**Pull request by crodriguez**
add spaces between = left and right sides

Hi I'm a new user, this is my first commit for emesene, please be nice!!! =)

### CODE REVIEW

**Comment by Sbte** [comment]
Maybe you could try to work on a different file. Someone else already seems to be doing this one : #783

**Comment by crodriguez** [comment]
Aps, thanks for the information, I will work in other file, can you recommend me another?

**Comment by Sbte** [comment]
If you're committing only pylint fixes and no 'real' fixes, I guess it doesn't really matter...

**Comment by c10ud** [comment]
closing till new developer action
specifically, https://github.com/emesene/emesene/pull/794#commitcomment-543787

**Pull request closed without merging**
