### PR TITLE
Qt4

### PR DESCRIPTION
**Pull request by GVisconti84**
Although C10ud said 'pulled' to my last pull request, it does'nt seem like the commits were actually pulled, so here's a pull request after having removed the merge branches :)

### CODE REVIEW

**Comment by GVisconti84** [comment]
Oh, if these commit were actually pulled, just close and ignore this request ;)

**Comment by c10ud** [comment]
argh, i pulled but forgot to push to emesene master lol

**Comment by c10ud** [comment]
ok done, now i'll add you to the emesene-whatever organization so you can push directly to emesene/master :)

**Comment by GVisconti84** [comment]
ehehehe ok, thanks ;) Don't forget to give me some pointer about how to do it without messing around :D

**Comment by c10ud** [comment]
well just keep the clean straight line in emesene/master (so no "merge.." commits or something) and we'll all be happy (except who doesn't like it :P) when committing just check it's a fast-forward, should be enough.. we wrote some git commands to help us remember, but now i can't remember where they are..probably @sbte does. anyway, i've seen you have some l33t skill with git, just don't remove the repo, everything else is fixable, lol

**Comment by GVisconti84** [comment]
Ok, great, I'll try to do my best :)
(Leet skills? You must be joking... :P)

**Comment by Sbte** [comment]
@c10ud, no clue what commands you mean.

@Whisky84, Try to push to your own branch first to see if that works fine. Then just pull it to the branch that's synced with the upstream branch (pull from the upstream branch first), and then push. And always make sure there are no merge commits before you push.

**Comment by Sbte** [comment]
Oh, and if you have questions: #emesene on FreeNode.

**Comment by GVisconti84** [comment]
Ok, I think I got it, thanks :)
Oh, btw, I guess I will receive a notification from github when I will be able to push directly, right?

**Comment by c10ud** [comment]
ok, you have been added :)

**Pull request merged**
