### PR TITLE
Move AvatarManager to gui.base

### PR DESCRIPTION
**Pull request by GVisconti84**
DISCLAIMER: don't pull before properly testing and inspecting the code :D

Ok, seriously, I've tested the code a bit, and it seems to work, but it's always better to doublecheck :)

Take also a look at what I've done, and decide if you like it, or if it is crap :P

It could be useful to clone branch `master2` of my repo and do tests faaaar away from your local copies of emesene2 repo :)

### CODE REVIEW

**Comment by c10ud** [comment]
wow, that was fast! i'll try it asap!

**Comment by c10ud** [comment]
just tried, it works good, i'll wait for wariano's OK, but the pull is ready to go

**Comment by GVisconti84** [comment]
Heheheheh wait wait, I didn't do everything today! ;);) I started to work on this a couple of days ago ;)

**Comment by c10ud** [comment]
pulled!

**Pull request closed without merging**
