### PR TITLE
#896 trick to close tabs with middle-click

### PR DESCRIPTION
**Pull request by lfottaviano**
Hi 
This is a small and good trick, that does the job!
But I know is cuestionable.
I wait your feedback.

### CODE REVIEW

**Comment by c10ud** [comment]
i tried pulling the threading part but i get a broken contact list when loading emesene

i have:
order by group
show..show blocked contacts
show..sort by name

**Comment by lfottaviano** [comment]
I am not at home right now. I will take a look when i am back.

**Comment by lfottaviano** [comment]
c10ud, I cant reproduce the problem, both emesene/emesene and my fork shows me identical contacts lists. under the same conditions: 

order by group
show..show blocked contacts
show..sort by name

-> Both versions sometimes dont show any group and leave the online contacts without parent on the tree.  Is this what you see?

**Comment by lfottaviano** [comment]
I am back again, I could reproduce it, it not always occurs, and apparently only occurs when logging in, I will be taking a look on it

**Comment by lfottaviano** [comment]
Well, the reason seems to be that contacts totals are yet being updated or received through the protocol while the thread is already running. I mean amount of online contacts and amount of total contacts.

Sometimes inside method _visible_func(): function self.contacts.get_online_total_count(contacts) (session object) returns 0, if you give it time this will return the corresponding value, but it could be too late and group will be set to visible=false.

You will see that if you run emesene, with "show empty groups"  at first load, this will work good.
This is because with that option enabled,  the amount of online contacts will not be evaluated ir order to modify the model and groups visibility will not be altered.

**Pull request merged**
