### PR TITLE
this is my first fix for the project

### PR DESCRIPTION
**Pull request by alonjimo**
add space following by a comma

hi I'm Alonso Jimenez, I'm from Costa Rica, I'm new here, i like programming and help in everything i can... please check if the thing I did is ok.. if not... please excuse me and teach me how to do it... i'll be pleased to contribute on the project on whatever you want... thnxs :)

### CODE REVIEW

**Comment by c10ud** [comment]
Hello, welcome and thanks for your contribution!
I'll see the diff and comment directly on code if there's something i don't understand

**Comment by c10ud** [comment]
ok, other than the few comments that i added (i'm not really sure about those **init** direct calls for simple variables) the diff looks good...we'll see what other say about those

**Comment by Sbte** [comment]
Any news on this?

**Comment by c10ud** [comment]
closing till new developer action

**Pull request closed without merging**
