### PR TITLE
Growl Notification plugin

### PR DESCRIPTION
**Pull request by ghost**
Pull request to include the growl plugin for OS X i developed. Its good to go now :)

### CODE REVIEW

**Comment by Sbte** [comment]
Could you possibly turn all this into one commit? This commit log is really hard to read :P

**Comment by ghost** [comment]
How would i do that?

**Comment by ghost** [comment]
One way is to backup the files you altered, delete your repo, fork the emesene repo, and commit the changes the newly forked repo.

**Comment by Sbte** [comment]
A better way would have been 

git reset --soft upstream/master
git commit -a -v

**Pull request closed without merging**
