### PR TITLE
papyon: ported and fixed lfrb direct connect patch

### PR DESCRIPTION
**Pull request by c10ud**
DO NOT PULL THIS
DO NOT PULL THIS
DO NOT PULL THIS
DO NOT PULL THIS
DO NOT PULL THIS

### CODE REVIEW

**Comment by c10ud** [comment]
i added a PR so we can have all the comments on the code.

i tested LOCAL emesene-to-emesene, direct connection works. sometimes it fails but restarting the transfer is enough

**Comment by astagi** [comment]
How does it work?
On Apr 22, 2012 6:02 PM, "Riccardo" <
reply@reply.github.com>
wrote:

**Comment by c10ud** [comment]
[19:07] <c10ud> pepeleproso, thing is i only tested emesene-to-emesene local
[19:07] <c10ud> because i think i have a too old amsn
[19:08] <c10ud> and wlm refused to do direct
[19:08] <c10ud> so sb fallback did fail a bit
[19:08] <c10ud> but worked sometimes
[19:08] <c10ud> i want more testing because this patch has some things
that i don't fully comprehend
[19:08] <c10ud> in general it's a: we send a filetransfer request
[19:09] <c10ud> the other party responds with a transreq or with nothing
[19:09] <c10ud> based on the repsonse we connect to them or send
through swithcboard
[19:09] <c10ud> same thing the other way inverse
[19:10] <c10ud> thing is, there's some data exchange in direct
connection i only tested emesene-to-emesene so i'm not sure it's 100%
correct
[19:10] <c10ud> also, port mapping IS tricky
[19:10] <c10ud> so the fallback needs to be _really_ tested

2012/4/22 Andrea Stagi
reply@reply.github.com:

**Comment by astagi** [comment]
Oh ok, I just had a fast look at the code.. so with this patch you create a
p2p connection between two clients that are using papyon, bypassing wlm
servers, don't you?

On Apr 22, 2012 7:11 PM, "Riccardo" <
reply@reply.github.com>
wrote:

**Comment by c10ud** [comment]
actually, this _should instead be_ the way direct connection works, papyon or not

the fact i tested emesene-to-emesene only is because i don't have access to WLM nor other clients i trust good enough to handle it

**Pull request merged**
