### PR TITLE
Some more fixes to Media message (Revert to PM with None and Music Note)

### PR DESCRIPTION
**Pull request by Mystro256**
Added a music note, this seems to be the closest to the frontend as I could find, please correct me if I'm wrong, because I'm shooting in the dark here.

Also made set_media(None) revert to personal message, this did seem to be apart of the handle what so ever, but I did make changes, which seemed to make things work with my change in the other method.

This was testing with Pidgin and the official client, things seem to work quite well.

### CODE REVIEW

**Comment by ghost** [comment]
Seems to break the iTunes and Spotify plugin on OS X

**Comment by Mystro256** [comment]
Really? Can you determine the source of the issue at all? Also, did you note the changes I pulled in the supported plugins? https://github.com/emesene/emesene-supported-plugins/pull/24

**Comment by ghost** [comment]
Tried that. Error log:  

File "/Applications/emesene.app/Contents/Resources/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/papylib/Worker.py", line 1121, in _handle_action_set_media
    self.session.media_change_succeed(message[0] + " - " + message[1])
TypeError: 'Song' object does not support indexing

**Comment by Mystro256** [comment]
As I said, my recent pull in supported plugins changes the song variable from a String to a Tuple, if you don't apply this change, this error is expected. It's trying to index something that can't be indexed, because it's expecting a tuple. Test with my tree for supported plugins, because the change hasn't been pulled yet.

**Comment by ghost** [comment]
Pulled your emesene fork and your plugin fork. Still doesnt work. Gives the same error above.

**Comment by Sbte** [comment]
Mystro, what player do you use to test with?

**Comment by Sbte** [comment]
Also, josh, did it also work for you before, say, last week?

**Comment by Mystro256** [comment]
I tested with Ubuntu and Banshee, I'm not quite understanding the issue here, as it looks like an issue is from message not being index-able. This should be an issue with songretriever.py, no? I'm not sure how this is happening with a different player...

**Comment by ghost** [comment]
Yeah it did. It would show current song, it was aware when itunes was closed/paused/playing etc. Message would not show in official client WLM though. But thats Papyons fault not mine right?

**Comment by Mystro256** [comment]
It was implemented, but it needed to be a tuple (index 0 being song, index 1 being artist) instead of a string to satisfy papyon, hence the changes I made. Take a look at these changes for reference of what I tried to do: https://github.com/emesene/emesene-supported-plugins/pull/24/files

**Comment by Sbte** [comment]
I'm not really into this stuff, but as far as I can see

The music plugin should set back the personal message:

https://github.com/emesene/emesene-supported-plugins/blob/master/music/songretriever.py#L88
https://github.com/emesene/emesene-supported-plugins/blob/master/music/songretriever.py#L159

and should return a string:

https://github.com/emesene/emesene-supported-plugins/blob/master/music/songretriever.py#L147

If you derive it from BaseMusicHandler, it returns a Song object:

https://github.com/emesene/emesene-supported-plugins/blob/master/music/songretriever.py#L76

you changed both to tuples, so it seems like it should work..

**Comment by Mystro256** [comment]
@joshf

I get no errors with itunes selected in the listening menu, though I can't test legitimately on linux, I don't see any issues. Did you remember to remove the pyc files? You maybe still using some of the old code by accident. Also note to make sure you aren't using an old music plugin, by accident, as there is currently two folder that could conflict.

The preference window shouldn't have the option to change the format if your using my version.

**Comment by ghost** [comment]
Nope its not that. Did a fresh clone of your repo for both emesene and emesene plugins.

**Comment by ghost** [comment]
Right the plugin does not work properly with latest emesene/emesene either but does work with a version from the 14/06/11. So it must be some other code change that has messed things up for OS X.

**Comment by Sbte** [comment]
Mystro, in your commit, how is this supposed to work:
-            song = (song.title, song.artist)

and this in the other method:
-                    self.session.set_media(song)

for both methods you should do something like:

song = self.get_current_song()
current_title = (song.title, song.artist)
self.session.set_media(current_title)

That'd fix josh's issues.

**Comment by c10ud** [comment]
pulled

**Comment by c10ud** [comment]
whoops i didn't see something was wrong (reading sbte?) anyway, just give me a new commit to pull D:

**Comment by Sbte** [comment]
It's a bug on the plugin repo side. Nothing wrong here I guess.

**Comment by c10ud** [comment]
kthxbi

**Comment by Mystro256** [comment]
Thanks, I'll make the changes right away to the plugin and repull.

**Comment by Mystro256** [comment]
Done, https://github.com/emesene/emesene-supported-plugins/pull/25

Thanks @Sbte for spotting my mess up :)

**Pull request closed without merging**
