### PR TITLE
Sorting emoticons

### PR DESCRIPTION
**Pull request by hit**
Sort emoticons in dialog by shortcut name so they can be more easily found. Also groups together emoticons with similar shortcuts for better overview.

### CODE REVIEW

**Comment by Mystro256** [comment]
I agree with Sbte, seems like sorting the custom emotions wouldn't be ideal because the user would expect it to be in the order that they added them. Maybe adding an option in the preference window, with it disabled by default?

**Comment by Sbte** [comment]
I don't think this is worth the trouble of adding another option. 

Also, I'm not sure if turning this into a plugin is possible, unless you reregister the dialog class, derive it from the internal dialog class, override select_emote to use your own EmotesWindow derived from the internal EmotesWindow and sort it there. Unless of course there's some other way I don't see.

**Comment by ivanalejandro0** [comment]
in my opinion is a great idea to sort the custom emoticons.
In my case i have many emoticons, i remember the position of the default ones and search for the custom ones by the shortcut.
Anyway, maybe my usage is not like the average, but i have to say that not everyone espects a particular order.

My 2 cents. Regards.

**Comment by c10ud** [comment]
well, i think we should sort both default and custom -- while keeping custom separate from default ones.. does this patch do that?

**Comment by Sbte** [comment]
No, it sorts only the custom ones in a place where you can't sort the default ones.

I tried to sort the default ones in a non-lame way but was unable to do that. Smileys first.

**Comment by hit** [comment]
Anyway, newly added emoticons are NOT always the last ones so the listing currently is kind of chaotic.

**Pull request closed without merging**
