### PR TITLE
gui: add support for opening url by preffered application in xfce

### PR DESCRIPTION
**Pull request by lefthaha**
Python's webbrowser module only detect "Gnome" and "KDE" desktop environment
xfce user is unable to open url by preffered application (eg. chromium is my default browser, but emesene always open url in firefox )
So I modified gui/base/Desktop.py, add support for xfce, replace webbrowser.open() with Desktop.open()

I am not familiar with gui, hope I am not creating more bugs  XD
and Thanks for all developer's effort :)

### CODE REVIEW

**Comment by c10ud** [comment]
nice! well you could complete the job and call webbrowser directly from the gui.base.Desktop module so you avoid the ugly try..except chain in cefc8378a4cd7834a288eb9a242d3db8543eb59b

**Comment by lefthaha** [comment]
@c10ud fixed, I also found a bug in Desktop.py when testing :)

btw. I just used git push --force to cancel previous commit, but I can still found canceld commit on github's personal  page 
and also on
https://github.com/emesene/emesene/commit/cefc8378a4cd7834a288eb9a242d3db8543eb59b

that's pretty strange...

**Comment by c10ud** [comment]
ok, i pulled your changes in emesene/master

**Comment by c10ud** [comment]
please try if i forgot something! and thanks for the changes!

**Comment by lefthaha** [comment]
I forgot to remove " import webbrowser " from those modified files.    (@ @)a
Here's the fix
a5c01758e598c75858d16d0506704556861eead6

**Comment by c10ud** [comment]
right, pulled thanks! :)

**Pull request closed without merging**
