### PR TITLE
Issue #821 (at least in GTK)

### PR DESCRIPTION
**Pull request by bubuntux**
Only show the close tab button if has only one tab (at least in GTK)

### CODE REVIEW

**Comment by bubuntux** [comment]
I'm sorry about the issue duplication, i didn't know to a pull request generate a new issue, please accept me change it's something very simple but looks more cleaner when don't use tab conversations.

**Comment by bubuntux** [comment]
What about now??
the 4 commits on my repository will be sent as like one commit in the principal repository??

**Comment by Sbte** [comment]
Now, if I pull them they will be four commits here too. To turn them into one commit, you have to do:

```
git reset --soft HEAD~4
git commit -a -v
git push -f
```

And name it something like:

```
gui.gtkui: Hide the close tab button when only one tab is present

Closes #821
```

It's descriptive as it should be and the last line will automagically close the corresponding issue here on github. You don't have to name 822 too, because that commit is the pull request.

**Comment by Sbte** [comment]
Oh, the changes look right btw. So that's good ;)

**Comment by bubuntux** [comment]
Done, everything it's in one single commit :)
I know it's something very simple but of this way looks more cleaner.

**Comment by Sbte** [comment]
Pulled, thanks!

**Pull request merged**
