### PR TITLE
Added two commits involving the help format button

### PR DESCRIPTION
**Pull request by Mystro256**
I fixed the button to not assume if the format is not nick, assume it's the group format help (see Dialog.py file change). The else case has been set to "...Help Does Not Exist." This is useful for plugins that use append_entry_default from gui.gtkui.Preferences (BaseTable class).

I also added in the help menu information for the music plugin into Dialog.py. I'm not sure if this is the desired method of implementation, as the method for showing help doesn't seem to be currently extendable for plugins. I committed it separately in case this is undesirable and needs to be cherry picked.

Also, on a side note, why does it say 12 commits? I only made 2 after pulling from emesene/emesene? Is there something about github I'm not getting?

Thanks

### CODE REVIEW

**Comment by c10ud** [comment]
well, pulling isn't always ok, the best way to get back on track with emesene/master is, sbte says:

git reset --hard emesene/master

**Comment by c10ud** [comment]
anyway tell me about the relevant commits and i'll cherry pick em so you can run the command after that :D

**Comment by Mystro256** [comment]
Haha, okay I'll do that from now on then. The relevant commits are the last 2 (Fixes up the format help dialog, and, Added Music format help (cherry pick if unwanted)). The pull request description above is the info for what I did.

Also, I forgot to tie my username to one of the commits, I can fix it if it's an issue.

**Comment by c10ud** [comment]
since there are a few typos and no i18n in the strings you added, just revert the commits and do them on a clean tree! :D then reopen the pull request

**Comment by pepeleproso** [comment]
Later i will fix the X button is the same fix we use for the preferences dialog.

**Comment by Mystro256** [comment]
Hmmmk, this just can be a temporary workaround then.

**Pull request closed without merging**
