### PR TITLE
i18n: New Module Language

### PR DESCRIPTION
**Pull request by lfottaviano**
I have a notebook with winbugs in english (for work), and I wanted emesene to be in spanish, and I didnt find a way to change the language from interface.

Please read the FIXME's and TODO's in the code.

I need to know how I can save an application variable,
I think there is another application variable being saved, no? 

I know the new combobox looks horrible and poor intuitive for common users, that is another TODO.

I think I am forgetting to say something lol

EDIT:
- I think all @sbte suggestions has been added
- Please, let me know, if the way I am saving the application config variable "language_config" is the correct way.
- I have tested this code on archlinux and windows and is working fine.

Good night.

### CODE REVIEW

**Comment by Sbte** [comment]
I just gave some commits on IRC. Don't push this yet ;)

**Comment by c10ud** [comment]
i wanted to pull this, but maybe we'll release 2.12.3 first for all *buntu users..i want to get more testing on this patch before making it a release

also, since it's mostly for windows, we can still have a 2.12.3+language patch for windows builds ;)

**Comment by lfottaviano** [comment]
good, no problem.  Yes the double instancing isn't needed, mistake

**Comment by lfottaviano** [comment]
When you test, you will see that are various reasons why the application doesn't get completely translated, those buttons and widgets that their strings are being reseolved by gtk (internally*) I think?
Examples: Accept, Cancel, About, Exit, Connect, Disconnect.

**Comment by c10ud** [comment]
yes, they're handled by gtk in system-wide translation - i wouldn't
know how to change that too (and in order to change it, language must
be available which isn't always true in linux..in windows we ship with
every gtk translation iirc)

2012/4/2 Lucas F. Ottaviano
reply@reply.github.com:

**Comment by c10ud** [comment]
a possible solution is the creation of a gui.base module that handles
all the strings in the code so we have complete control over
translation (or e3.whatever, since iirc we use translations also in
other parts outside of gui)

2012/4/2 Riccardo (c10ud) c10ud.dev@gmail.com:

**Comment by c10ud** [comment]
what to do with this pr then? pull? wait? other?

**Comment by lfottaviano** [comment]
I have a commit that does what arielj said, but I couldnt get time to push
the commit, I will see If I can do it today

2012/4/4 Riccardo <
reply@reply.github.com

> what to do with this pr then? pull? wait? other?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/pull/1112#issuecomment-4959298

## 

Lucas F. Ottaviano.

**Comment by Sbte** [comment]
@c10ud, ok so this is what I hate about merges. Instead of the new commits being on top, they're now scattered somewhere between the old commits. There's even new commits BEFORE 2.12.3. Just so you know ;)

**Pull request merged**
