### PR TITLE
Fixes #650, also a gnome 3 fix

### LINKED ISSUE #650: session.set_media doesn't do anything
I was testing the music plugin to fix issues and whatnot, but session.set_media() does seem to do anything. I have tested it with the official client and multiple emesene sessions. There doesn't seems to be any acknowledgement of anything when I use session.set_media(STRING).

Is this a papyon glitch or emesene? or is this a yet to be implemented functionality?

I'm using papyon version 0.5.5-1ubuntu1.2

### PR DESCRIPTION
**Pull request by Mystro256**
Allows set_media to actually work properly, but doesn't allow a custom music
format unfortunately, this will have to be worked on later if it's still wanted.
Unfortunately this is the only way to get it working for now, see #650.

<b>EDIT: I also included the fix to add the X on the hint/format help dialogs in preferences.</b>

### CODE REVIEW

**Comment by Mystro256** [comment]
Also posting a pull request on the supported plugins to accommodate these changes in the music plugin

**Comment by Sbte** [comment]
Ah, ok. Sorry. Weird stuff though. That you can't send a string to papyon...

Anyway, the indentation still seemed wrong

**Comment by Mystro256** [comment]
Well I added another commit but seems c1oud has doubts about my implementation

Edit: Scratch that, see below

**Comment by Mystro256** [comment]
I removed the note, fixed the indent, and it's all in one pretty commit ;)

**Comment by Mystro256** [comment]
Also fixed the hint/format help dialogs in preferences because they were troublesome :P

**Pull request merged**
