### PR TITLE
Add option to disable dock icon on OS X

### PR DESCRIPTION
**Pull request by ghost**
Hide the dock icon for the emesene launcher on OS X

### CODE REVIEW

**Comment by Sbte** [comment]
Please recommit the new changes:

```
git reset --soft HEAD^^
git commit -a -v -c ORIG_HEAD
git push -f
```

**Comment by Mystro256** [comment]
I would also like to see this on gnome-shell as well. Speaking of gnome shell, is there any integration with gnome-shell yet?

**Comment by ghost** [comment]
Done

**Comment by Sbte** [comment]
@Mystro256, don't think so.

@joshf, just one more thing. Could you change the commit message? My mistake in the commands I gave you. It now uses the message for the fixes.

```
git reset --soft HEAD^
git commit -a -v
git push -f
```

That should allow you to write a new one ;)

**Pull request merged**
