### PR TITLE
fix bug on login status 

### PR DESCRIPTION
**Pull request by shwangdev**
fix bug on user login status

### CODE REVIEW

**Comment by shwangdev** [comment]
@sbte I have refined the issue, please help to verify the code.

**Comment by Sbte** [comment]
Well, I guess that works, if your session supports all that. Other than that, I think you should still set the capabilities correctly (otherwise the login window will not work correctly for your session).

Once you fix that, please turn all commits into one commit using interactive rebase and give it a meaningful commit message. "refine bug" doesn't tell anyone anything.

**Comment by shwangdev** [comment]
*Got u.
*
On Tue, Aug 28, 2012 at 8:18 PM, Sven notifications@github.com wrote:

> Well, I guess that works, if your session supports all that. Other than
> that, I think you should still set the capabilities correctly (otherwise
> the login window will not work correctly for your session).
> 
> Once you fix that, please turn all commits into one commit using
> interactive rebase and give it a meaningful commit message. "refine bug"
> doesn't tell anyone anything.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/emesene/emesene/pull/1492#issuecomment-8089519.

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_

**Comment by shwangdev** [comment]
I have done rebase interactive with the two commits as one commit , please merge to master branch.

**Comment by Sbte** [comment]
Could you also make a commit to properly set the capabilities?

**Comment by c10ud** [comment]
i'll pull this meanwhile

**Pull request merged**
