### PR TITLE
Groupping Menu 'copy contact information' in conversation

### PR DESCRIPTION
**Pull request by jamesaxl**
\0/

### CODE REVIEW

**Comment by Sbte** [comment]
The text is different from the other commit you submitted. This is not efficient for translations.

Also, please try to extract this menu, since you use it twice (in the header and the contact information menu).

And don't open a new pull request when you commit this. This one will update automatically.

**Comment by c10ud** [comment]
is it good now? strings seem correct (+1 new one)

**Comment by Sbte** [comment]
No, not good. Compare strings added in the above commit to strings added in the previous commit:

https://github.com/emesene/emesene/commit/4ab70e8a757b1b98c6884dec26d562fe95d71ecf

We don't need two different strings for the same thing. Also, this menu can be extracted. Doing this will fix the problem with the strings.

**Comment by c10ud** [comment]
@jamesaxl i will pull this but you must address the issues @Sbte pointed out first (and maybe my little one too :D)

**Comment by c10ud** [comment]
please reopen once you addressed those issues

**Pull request closed without merging**
