### PR TITLE
Single window emesene

### PR DESCRIPTION
**Pull request by c10ud**
ladies and gentlemen, i tried skypetab-ng and it's awesome so today i decided to quickly hack something for emesene-gtk.

known issues:
- disconnecting breaks everything!
- some positioning/dimensions bugs

please fix the issues and give me patches so we can enjoy a fully feature single-window emesene!

greets

@sbte

### CODE REVIEW

**Comment by lfottaviano** [comment]
for `disconnecting breaks everything` :

https://github.com/lfottaviano/emesene/commit/39400f6db086313f2ff85381c40ae943b006a98c

but shouldn't be all.

**Comment by c10ud** [comment]
did you check that it works when the single window option isn't used? otherwise i will investigate this later

**Comment by c10ud** [comment]
pulled in your change

**Comment by c10ud** [comment]
i suspect self.cb_on_close(self.content_main) in Window.py it's in our way, because we have different callbacks for different content..

**Comment by c10ud** [comment]
in b4: i make use of hide_all again but it fails when single window isn't used

**Pull request merged**
