### PR TITLE
Fixed Odd Sound Issues

### PR DESCRIPTION
**Pull request by Mystro256**
Fixes issue #433, my apologies if this isn't committed right, I'm kind of new to this :P

### CODE REVIEW

**Comment by Sbte** [comment]
It's all done right, but you  probably want your name set and your email fixed (so your name is clickable ;)). To do that, do

git config --global user.name "Your Name"
git config --global user.email "me@example.com"

And then redo your last commit.

git reset --soft HEAD^
git commit -a -c ORIG_HEAD

**Comment by Mystro256** [comment]
Thanks!

Although I don't think the code you gave me worked, but oh well, as long as the commit worked I'm happy :)

**Comment by c10ud** [comment]
what exactly did you change in the files, btw?

**Comment by c10ud** [comment]
pulled

**Comment by Mystro256** [comment]
For some odd reason the sounds didn't play right on my Ubuntu installs. I seemed to fix this issue by converting the *.wav files to *.mp3 and back. There doesn't appear to be any loss of quality from my end.

**Comment by c10ud** [comment]
i see, well, glad to see it's solved now

2011/4/20 Mystro256
reply@reply.github.com:

**Pull request closed without merging**
